sudo: true
dist: trusty
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
branches:
  only:
  - master
before_script:
  - echo "composer install"
  - wget https://getcomposer.org/download/1.7.2/composer.phar -O ./composer
  - chmod +x ./composer
  - sudo mv ./composer /usr/local/bin/
  - echo "phpunit install"
  - wget https://phar.phpunit.de/phpunit-5.phar -O ./phpunit
  - chmod +x ./phpunit
  - sudo mv ./phpunit /usr/local/bin/
  - echo "ocular install"
  - wget https://scrutinizer-ci.com/ocular.phar -O ./ocular
  - chmod +x ./ocular
  - sudo mv ./ocular /usr/local/bin/
script:
  - /usr/local/bin/composer install --no-dev
  - /usr/local/bin/phpunit -c phpunit.xml --colors=always
  - /usr/local/bin/phpunit --coverage-clover=coverage.clover
  - /usr/local/bin/ocular code-coverage:upload --format=php-clover coverage.clover
before_deploy:
  - php -d phar.readonly=0 build/make-phar.php
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build/deploid.phar
  skip_cleanup: true
  on:
    repo: userator/deploid
    php:  '5.6'