language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
sudo: false
branches:
  only:
  - master
script:
    - ./vendor/bin/phpunit -c phpunit.xml --colors=always
before_deploy:
    - php -d phar.readonly=0 build/make-phar.php
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build/deploid.phar
  skip_cleanup: true
  on:
    tags: true
    repo: userator/deploid
    php:  '5.6'