language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
sudo: true
branches:
  only:
  - master
before_script:
  - echo "comspoer install"
  - wget https://getcomposer.org/download/1.7.2/composer.phar -O ./composer
  - chmod +x ./composer
  - mv ./composer /usr/local/bin/
  - echo "phpunit install"
  - wget https://phar.phpunit.de/phpunit-5.phar -O ./phpunit
  - chmod +x ./phpunit
  - mv ./phpunit /usr/local/bin/
script:
  - /usr/local/bin/composer install --no-dev
  - /usr/local/bin/phpunit -c phpunit.xml --colors=always
before_deploy:
    - php -d phar.readonly=0 build/make-phar.php
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build/deploid.phar
  skip_cleanup: true
  on:
    tags: true
    repo: userator/deploid
    php:  '5.6'