<?php

namespace Deploid;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-10-17 at 21:55:10.
 */
class PayloadTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Payload
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Payload;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Deploid\Payload::getCode
	 * @todo   Implement testGetCode().
	 */
	public function testGetCode() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Deploid\Payload::getType
	 * @todo   Implement testGetType().
	 */
	public function testGetType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Deploid\Payload::getMessage
	 * @todo   Implement testGetMessage().
	 */
	public function testGetMessage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Deploid\Payload::setCode
	 * @todo   Implement testSetCode().
	 */
	public function testSetCode() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Deploid\Payload::setType
	 * @todo   Implement testSetType().
	 */
	public function testSetType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Deploid\Payload::setMessage
	 * @todo   Implement testSetMessage().
	 */
	public function testSetMessage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Deploid\Payload::toArray
	 * @todo   Implement testToArray().
	 */
	public function testToArray() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}